### ISSUE TITLE
[ClickableMentions] crashed after tap in an embed mention 

### ISSUE THREAD

**Issue by Ichigo271** [DiamondMiner88/aliucord-plugins#25]
java.lang.IllegalStateException: Fragment WidgetChatList{2d64ea3} (45ee7de6-aaef-4128-9061-bd12369177d4)} not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:2)
	at com.discord.widgets.chat.list.adapter.WidgetChatListAdapterEventsHandler.getFragmentManager(WidgetChatListAdapterEventsHandler.kt:1)
	at com.discord.widgets.chat.list.adapter.WidgetChatListAdapterEventsHandler.onUserMentionClicked(WidgetChatListAdapterEventsHandler.kt:1)
	at com.github.diamondminer88.plugins.ClickableMentions$userClickHandler$1.invoke(ClickableMentions.kt:31)
	at com.github.diamondminer88.plugins.ClickableMentions$userClickHandler$1.invoke(ClickableMentions.kt:26)
	at com.discord.utilities.textprocessing.node.UserMentionNode$renderUserMention$1.invoke(UserMentionNode.kt:2)
	at com.discord.utilities.textprocessing.node.UserMentionNode$renderUserMention$1.invoke(UserMentionNode.kt:1)
	at com.discord.utilities.spans.ClickableSpan.onClick(ClickableSpan.kt:1)
	at com.discord.utilities.view.text.LinkifiedTextView$ClickableSpanOnTouchListener.onTouch(LinkifiedTextView.kt:26)
	at android.view.View.dispatchTouchEvent(View.java:15110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3199)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4410)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529)
	at android.view.View.dispatchPointerEvent(View.java:15398)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7154)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6907)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6322)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6379)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6345)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6510)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6353)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6567)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6326)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6379)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6345)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6353)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6326)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9601)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9552)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9507)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9749)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:296)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:169)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8227)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by rushiiMachine** [comment]
Not fixable
