### ISSUE TITLE
Freeze discord and crash audioplayer

### ISSUE THREAD

**Issue by attiq-apg** [DiamondMiner88/aliucord-plugins#28]
When I go to a channel which have a voice message or scroll to a voice note or if i somehow play a file it freeze and crash discord fix it plsss 😐

**Comment by rushiiMachine** [comment]
crashlog?

**Comment by attiq-apg** [comment]
I re installed it today but now it associates a single voice note to all of the files 🤦

**Comment by attiq-apg** [comment]
I re installed it today but now it associates a single voice note to all of the files 🤦
Uh oh happened again this time it didn't log crash but found this in debug logs "[VoiceMessages] Error:
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.discord.api.channel.Channel.i()' on a null object reference
  at com.aliucord.wrappers.ChannelWrapper$Companion.getGuildId(ChannelWrapper.kt:151)
  at com.aliucord.wrappers.ChannelWrapper.getGuildId(ChannelWrapper.kt:47)
  at com.aliucord.plugins.VoiceMessages.showVoiceChannelIconIfCan(VoiceMessages.java:261)
  at com.aliucord.plugins.VoiceMessages.lambda$start$4$com-aliucord-plugins-VoiceMessages(VoiceMessages.java:171)
  at com.aliucord.plugins.VoiceMessages$$ExternalSyntheticLambda6.call(Unknown Source:4)
  at com.aliucord.patcher.Hook.afterHookedMethod(Hook.kt:21)
  at de.robv.android.xposed.XposedBridge$HookInfo.callback(XposedBridge.java:381)
  at LSPHooker_.handleChannelSelected(Unknown Source:15)
  at com.discord.stores.StoreStream.access$handleChannelSelected(StoreStream.kt, [VoiceMessages] Error::1)
  at com.discord.stores.StoreStream$deferredInit$1$5.invoke(StoreStream.kt:2)
  at com.discord.stores.StoreStream$deferredInit$1$5.invoke(StoreStream.kt:1)
  at com.discord.stores.StoreStream$dispatchSubscribe$1$1.invoke(StoreStream.kt:2)"

**Comment by rushiiMachine** [comment]
> com.aliucord.plugins.VoiceMessages
That is not my plugin, that is mantikafasi's

Otherwise, Audioplayer currently has bugs
